### ISSUE TITLE
Add connection speed?

### ISSUE THREAD

**Issue by anselmh** [Data-Info-API/Architecture#10]
Actually there are data plans that don’t offer 4G for example. 
Shouldn’t that also be an information to get via the API?

Of course that doesn’t provide any info on the actual speed but it gives a hint on if such a connection could ever be reached or not.

**Comment by kevinprince** [comment]
Couple of options here you kind of want bearer i thnk (2g, 3g / 4g (all the flavours)).

Issue from a developer perspective is "what is 4G" for example ATT were marketing HSDPA++ as 4G

**Comment by anselmh** [comment]
Yes, I agree that it’s hard to do this distinction but I think 2g, 3G, 4G help and HSDPA++ is likely only marketed as 4G but not served as such so it won’t be an issue to differentiate between LTE and HDPA(+/++) in my opinion.

But that said it’s only a suggestion to bear in mind.

**Comment by igrigorik** [comment]
I don't believe this is necessary, as the client should already have access to this information via NetInfo API: http://w3c.github.io/netinfo/

**Comment by anselmh** [comment]
Okay cool, think you’re right then @igrigorik. Therefore closing this request.

**Comment by nrooney** [comment]
Thanks for the suggestion guys - we had some issue in W3C with this previously. It turned out devs could assume "wifi" was faster than 3G (or 4G) but this wasn't always the case. Although this helps with "downloading something over a data plan" use case it doesn't help with the "downloading something large because I'm on wifi" case. I know this doesn't answer @anselmh's question but does give some background!

I think understanding the use case for this would be good, and then see if it's around in any other spec. For instance, it might be better to extend the Network Info API with this than to include it here:
http://w3c.github.io/netinfo/

@marcosc will know!

**Comment by nrooney** [comment]
Urgh just wrote a wonderful reply to find Ilya had already sorted it! That teaches me for not responding quickly enough!
